In [ ]:
import numpy as np
import matplotlib.pyplot as plt

<p style="color: blue; font-size: 30px;"><b>Forward Pass</b></p>

hidden_layer_input = np.dot(X, weights_input_hidden) + bias_hidden           

X :      
[[0.5488135 0.71518937 0.60276338]]     

weights_input_hidden:     
[[0.84725174 0.6235637 ] [0.38438171 0.29753461] [0.05671298 0.27265629]] 

np.dot(X, weights_input_hidden) :       
[[0.77407341 0.71936099]]      

bias_hidden :     
[[0.47997717 0.3927848 ]]    

hidden_layer_input :    
[[1.25405058 1.11214579]]      

# Break this down step by step Forward Pass

**1. Understanding the Formula:**      
The expression:   

$$HiddenLayerInput = np.dot(X, WeightsInputHidden) + BiasHidden$$ 

represents a crucial step in a neural network. It calculates the input to the neurons in the hidden layer by performing:

* A matrix multiplication between the **input features (X)** and **the weight matrix (weights_input_hidden)**.

* Adding the **bias (bias_hidden)** to each **result for the neurons in the hidden layer**.

**2. Inputs and Parameters:** 

* X is the input data. It's a 1x3 matrix (a single sample with 3 features): $$ X = \begin{bmatrix} 0.5488135 & 0.71518937 & 0.60276338 \end{bmatrix} $$

 * weights_input_hidden is the weight matrix for the connections from the input layer to the hidden layer. It has a shape of 3x2, meaning there are 3 input features and 2 neurons in the hidden layer: $$ WeightsInputHidden = \begin{bmatrix} 0.84725174 & 0.6235637 \\ 0.38438171 & 0.29753461 \\ 0.05671298 & 0.27265629 \end{bmatrix} $$

* bias_hidden is the bias for the neurons in the hidden layer. It’s a 1x2 matrix (matching the number of hidden neurons): $$ BiasHidden = \begin{bmatrix} 0.47997717 & 0.3927848 \end{bmatrix} $$     


**3. Matrix Multiplication (np.dot):**       
The matrix multiplication (np.dot) computes the dot product of X and weights_input_hidden:

$$ np.dot(X, WeightsInputHidden) = \begin{bmatrix} 0.5488135 & 0.71518937 & 0.60276338 \end{bmatrix} \cdot \begin{bmatrix} 0.84725174 & 0.6235637 \\ 0.38438171 & 0.29753461 \\ 0.05671298 & 0.27265629 \end{bmatrix} $$ 


This results in: $$ np.dot(X, WeightsInputHidden) = \begin{bmatrix} 0.77407341 & 0.71936099 \end{bmatrix} $$

Here’s how each element is calculated:

First hidden neuron: $$ (0.5488135 \cdot 0.84725174) + (0.71518937 \cdot 0.38438171) + (0.60276338 \cdot 0.05671298) = 0.77407341 $$

Second hidden neuron: $$ (0.5488135 \cdot 0.6235637) + (0.71518937 \cdot 0.29753461) + (0.60276338 \cdot 0.27265629) = 0.71936099 $$


**4. Adding the Bias:**
To calculate hidden_layer_input, the bias is added element-wise to the result of the dot product: $$ HiddenLayerInput = \begin{bmatrix} 0.77407341 & 0.71936099 \end{bmatrix}

\begin{bmatrix} 0.47997717 & 0.3927848 \end{bmatrix} $$

This gives: $$ HiddenLayerInput = \begin{bmatrix} 1.25405058 & 1.11214579 \end{bmatrix} $$


**5. Interpretation:**     
The hidden_layer_input is the combined weighted sum of the inputs and biases for each neuron in the hidden layer.     

These values will typically be passed through an **activation function (like sigmoid, ReLU, etc.) to introduce non-linearity into the network**.      







# Let’s calculate the dot product step by step!



We are given:
$$\text{Vector } X = [0.5488135, 0.71518937, 0.60276338]$$

$$\text{Matrix } W (Weights Input Hidden) = \begin{bmatrix} 
0.84725174 & 0.6235637 \\ 
0.38438171 & 0.29753461 \\ 
0.05671298 & 0.27265629 
\end{bmatrix}$$

**Step 1: Definition**
The dot product involves multiplying corresponding elements of a vector and matrix row-wise and summing the results.    

For matrix multiplication, we calculate:

$$X \cdot W = 
\begin{bmatrix} 
x_1 & x_2 & x_3 
\end{bmatrix} \cdot 
\begin{bmatrix} 
w_{1,1} & w_{1,2} \\ 
w_{2,1} & w_{2,2} \\ 
w_{3,1} & w_{3,2} 
\end{bmatrix}$$

**Step-by-Step Calculation:**     

1. Multiply each element of the row in **X** with the corresponding elements in the columns of **weights_input_hidden**, summing up for each column.

**First Column:**   
( 0.5488135 × 0.84725174 ) + ( 0.71518937 × 0.38438171 ) + ( 0.60276338 × 0.05671298 ) 

Breaking it down:   
0.5488135 × 0.84725174 = 0.464898  

0.71518937 × 0.38438171 = 0.274936

0.60276338 × 0.05671298 = 0.034208  

Sum:

0.464898 + 0.274936 + 0.034208 = 0.774042


**Second Column:**  
(0.5488135 × 0.6235637) + (0.71518937 × 0.29753461) + (0.60276338 × 0.27265629) 

Breaking it down:     

0.5488135 × 0.6235637 = 0.342245

0.71518937  ×0.29753461 = 0.212861  

0.60276338  0.27265629 = 0.164392  

Sum:

0.342245+0.212861+0.164392= 0.719498

**Resulting Dot Product:**     
The result is a 1×2 matrix:       
  
[0.774042  0.719498]

## Calculating  np.dot(X, weights_input_hidden) + bias_hidden

so 
results = np.dot(X, weights_input_hidden) = [0.77407341, 0.71936099]     


bias_hidden = [0.47997717, 0.3927848 ]

To add these two vectors, simply sum their respective elements:    

[0.77407341 + 0.47997717 , 0.71936099 + 0.3927848]    

So the result is:    

[ 1.25405058 , 1.11214579 ]