In [10]:
import numpy as np
import matplotlib.pyplot as plt

# Sigmoid activation function and its derivative

In [13]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [15]:
def sigmoid_derivative(x):
    return x * (1 - x)

# Mean squared error loss

In [18]:
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Generate some dummy data
* Features (X): 100 samples, each with 3 features        
* Targets (y): Binary (0 or 1)    

In [39]:
np.random.seed(0)
X = np.random.rand(100, 3)
y = np.random.randint(0, 2, size=(100, 1))

In [41]:
X

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677],
       [0.43860151, 0.98837384, 0.10204481],
       [0.20887676, 0.16130952, 0.65310833],
       [0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959],
       [0.13818295, 0.19658236, 0.36872517],
       [0.

In [43]:
y

array([[0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
    

# Define the neural network structure

In [46]:
input_neurons = 3  # Number of features in the input
hidden_neurons = 2 # Number of neurons in the hidden layer
output_neurons = 1 # Binary output (0 or 1)

# Initialize weights and biases randomly

In [49]:
weights_input_hidden = np.random.rand(input_neurons, hidden_neurons)
weights_hidden_output = np.random.rand(hidden_neurons, output_neurons)
bias_hidden = np.random.rand(1, hidden_neurons)
bias_output = np.random.rand(1, output_neurons)

print( "Weights Input Hidden : \n"  + str(weights_input_hidden) + "\n")
print( "Weights Hidden Output : \n"  + str(weights_hidden_output) + "\n")
print( "Bias Hidden : \n" + str(bias_hidden) + "\n")
print( "Bias Output : \n" + str(bias_output) + "\n")

Weights Input Hidden : 
[[0.64557024 0.03536244]
 [0.43040244 0.51001685]
 [0.53617749 0.68139251]]

Weights Hidden Output : 
[[0.2775961 ]
 [0.12886057]]

Bias Hidden : 
[[0.39267568 0.95640572]]

Bias Output : 
[[0.18713089]]



# Training parameters

In [52]:
learning_rate = 0.1
epochs = 1000

# Print A Loop Function

In [55]:
def check_and_print(loopNum, loopPrint, message):
    # Check if loopNum is in loopPrint
    if loopNum in loopPrint:
        # Print the message
        print(message)

In [57]:
loopNum = 5
loopPrint = [1, 2, 3, 5]
message = "Match found!"
check_and_print(loopNum, loopPrint, message)

Match found!


# Training the network

In [60]:
for epoch in range(epochs):

    loopPrint = [0]
    check_and_print( epoch, loopPrint, "---------------------------------------- LOOP NUMBER : " + str(epoch)   + "----------------------------------------" )

    # Forward pass
    check_and_print( epoch, loopPrint, "______________________________ Forward Pass ______________________________ " )
    
    check_and_print( epoch, loopPrint, " X : \n" + str(X)  + "\n")
    check_and_print( epoch, loopPrint, " weights_input_hidden: \n" + str(weights_input_hidden)  + "\n")
    check_and_print( epoch, loopPrint, " np.dot(X, weights_input_hidden) : \n" + str(np.dot(X, weights_input_hidden))  + "\n")
    check_and_print( epoch, loopPrint, " bias_hidden : \n" + str(bias_hidden)  + "\n")
    hidden_layer_input = np.dot(X, weights_input_hidden) + bias_hidden
    check_and_print( epoch, loopPrint, " hidden_layer_input : \n" + str(hidden_layer_input) + "\n" )

    check_and_print( epoch, loopPrint, "______________________________ Sigmoid ______________________________" )

    check_and_print( epoch, loopPrint, " Hidden Layer Input : \n" + str(hidden_layer_input)  + "\n")
    hidden_layer_output = sigmoid(hidden_layer_input)
    check_and_print( epoch, loopPrint, " sigmoid(hidden_layer_input) : \n" + str(hidden_layer_output)  + "\n")

    check_and_print( epoch, loopPrint, "_____________________________________________________________________" )

    check_and_print( epoch, loopPrint, " hidden_layer_output : \n" + str(hidden_layer_output)  + "\n")
    check_and_print( epoch, loopPrint, " weights_hidden_output: \n" + str(weights_hidden_output)  + "\n")
    check_and_print( epoch, loopPrint, " np.dot(hidden_layer_output, weights_hidden_output) : \n" + str(np.dot(hidden_layer_output, weights_hidden_output))  + "\n")
    check_and_print( epoch, loopPrint, " bias_hidden : \n" + str(bias_hidden)  + "\n")
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    check_and_print( epoch, loopPrint, " output_layer_input : \n" + str(output_layer_input)  + "\n")

    check_and_print( epoch, loopPrint, "_____________________________________________________________________" )

    check_and_print( epoch, loopPrint, " output_layer_input : \n" + str(output_layer_input)  + "\n")
    output = sigmoid(output_layer_input)
    check_and_print( epoch, loopPrint, " output : \n" + str(output)  + "\n")

    check_and_print( epoch, loopPrint, "_______________________________ Compute Loss __________________________" )
    
    # Compute loss
    check_and_print( epoch, loopPrint, " y : \n" + str(y)  + "\n")
    check_and_print( epoch, loopPrint, " output : \n" + str(output)  + "\n")
    loss = mse_loss(y, output)
    check_and_print( epoch, loopPrint, " loss : \n" + str(loss)  + "\n")

    check_and_print( epoch, loopPrint, "_______________________________ Backward Pass __________________________" )
    
    # Backward pass
    check_and_print( epoch, loopPrint, " y : \n" + str(y)  + "\n")
    check_and_print( epoch, loopPrint, " output : \n" + str(output)  + "\n")
    error_output = y - output
    check_and_print( epoch, loopPrint, " error_output : \n" + str(error_output)  + "\n")

    check_and_print( epoch, loopPrint, "_____________________________________________________________________" )

    check_and_print( epoch, loopPrint, " error_output : \n" + str(error_output)  + "\n")
    check_and_print( epoch, loopPrint, " output : \n" + str(output)  + "\n")
    check_and_print( epoch, loopPrint, " sigmoid_derivative(output) : \n" + str(sigmoid_derivative(output))  + "\n")
    delta_output = error_output * sigmoid_derivative(output)
    check_and_print( epoch, loopPrint, " delta_output : \n" + str(delta_output)  + "\n")

    check_and_print( epoch, loopPrint, "_____________________________________________________________________" )

    check_and_print( epoch, loopPrint, " weights_hidden_output.T : \n" + str(weights_hidden_output.T)  + "\n")
    check_and_print( epoch, loopPrint, " delta_output.dot(weights_hidden_output.T) : \n" + str(delta_output.dot(weights_hidden_output.T))  + "\n")
    error_hidden = delta_output.dot(weights_hidden_output.T)
    check_and_print( epoch, loopPrint, " error_hidden : \n" + str(error_hidden)  + "\n")

    check_and_print( epoch, loopPrint, "_____________________________________________________________________" )

    check_and_print( epoch, loopPrint, " error_hidden : \n" + str(error_hidden)  + "\n")
    check_and_print( epoch, loopPrint, " hidden_layer_output : \n" + str(hidden_layer_output)  + "\n")
    check_and_print( epoch, loopPrint, " sigmoid_derivative(hidden_layer_output) : \n" + str(sigmoid_derivative(hidden_layer_output))  + "\n")
    delta_hidden = error_hidden * sigmoid_derivative(hidden_layer_output)
    check_and_print( epoch, loopPrint, " delta_hidden : \n" + str(delta_hidden)  + "\n")

    check_and_print( epoch, loopPrint, "____________________________________ Update weights and biases ________________________________" )
    # Update weights and biases
    check_and_print( epoch, loopPrint, " hidden_layer_output.T : \n" + str(hidden_layer_output.T)  + "\n")
    check_and_print( epoch, loopPrint, " delta_output : \n" + str(delta_output)  + "\n")
    check_and_print( epoch, loopPrint, " hidden_layer_output.T.dot(delta_output) : \n" + str( hidden_layer_output.T.dot(delta_output) )  + "\n")
    check_and_print( epoch, loopPrint, " learning_rate : \n" + str(hidden_layer_output.T.dot(learning_rate))  + "\n")
    weights_hidden_output += hidden_layer_output.T.dot(delta_output) * learning_rate
    check_and_print( epoch, loopPrint, " weights_hidden_output : \n" + str( weights_hidden_output )  + "\n")
    check_and_print( epoch, loopPrint, "_____________________________________________________________________" )

    check_and_print( epoch, loopPrint, " X.T : \n" + str(X.T)  + "\n")
    check_and_print( epoch, loopPrint, " delta_hidden : \n" + str(delta_hidden)  + "\n")
    check_and_print( epoch, loopPrint, " X.T.dot(delta_hidden) : \n" + str(X.T.dot(delta_hidden))  + "\n")
    check_and_print( epoch, loopPrint, " learning_rate: \n" + str(learning_rate)  + "\n")
    weights_input_hidden += X.T.dot(delta_hidden) * learning_rate
    check_and_print( epoch, loopPrint, " weights_input_hidden : \n" + str(weights_input_hidden)  + "\n")
    check_and_print( epoch, loopPrint, "_____________________________________________________________________" )

    check_and_print( epoch, loopPrint, " learning_rate : \n" + str(learning_rate)  + "\n \n")

    check_and_print( epoch, loopPrint, " delta_output : \n" + str(delta_output)  + "\n")
    check_and_print( epoch, loopPrint, " np.sum(delta_output, axis=0, keepdims=True) : \n" + str(np.sum(delta_output, axis=0, keepdims=True))  + "\n")
    bias_output += np.sum(delta_output, axis=0, keepdims=True) * learning_rate
    check_and_print( epoch, loopPrint, " bias_output : \n" + str(bias_output)  + "\n")

    check_and_print( epoch, loopPrint, "_____________________________________________________________________" )

    check_and_print( epoch, loopPrint, " learning_rate : \n" + str(learning_rate)  + "\n \n")

    check_and_print( epoch, loopPrint, " delta_hidden : \n" + str(delta_hidden)  + "\n")
    check_and_print( epoch, loopPrint, " np.sum(delta_hidden, axis=0, keepdims=True) : \n" + str(np.sum(delta_hidden, axis=0, keepdims=True))  + "\n")
    bias_hidden += np.sum(delta_hidden, axis=0, keepdims=True) * learning_rate
    check_and_print( epoch, loopPrint, " bias_hidden : \n" + str(bias_hidden)  + "\n")

    check_and_print( epoch, loopPrint, "_____________________________________________________________________" )

    # Print loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}/{epochs}, Loss: {loss:.4f}")



# Final output after training
print("\nTraining complete.")

---------------------------------------- LOOP NUMBER : 0----------------------------------------
______________________________ Forward Pass ______________________________ 
 X : 
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329]
 [0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033]
 [0.56843395 0.0187898  0.6176355 ]
 [0.61209572 0.616934   0.94374808]
 [0.6818203  0.3595079  0.43703195]
 [0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263 ]
 [0.31542835 0.36371077 0.57019677]
 [0.43860151 0.98837384 0.10204481]
 [0.20887676 0.16130952 0.65310833]
 [0.2532916  0.46631077 0.24442559]
 [0.15896958 0.11037514 0.65632959]
 [0.13818295 0.19658236 0.36872517]
 [0.82099323 0.09710128 0.837